### ISSUE TITLE
Introduce yourself

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2019#1]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. **Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Arlington, MA. In addition to this course, I also teach one of the capstone courses in Digital Media design. In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. 

More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by bret-blackford** [comment]
Bret here – 

I’m a St. Louis native (where it is currently :snowflake: **-4F** :snowflake:).  Family and a full-time job keep me plenty busy but my curiosity and joy of learning have kept me taking Extension courses for years.

I just finished [E-12]( https://canvas.harvard.edu/courses/52938/assignments/syllabus) last semester and really enjoyed the course and hope to continue with E-15.  Looking to better understand server-side code, *especially* managing state with database connectivity.

**Comment by mpswain** [comment]
Hi, I'm Michael, from Buffalo. (Yes, it's snowing.)

I too took E-12 last semester and this looked like a good next step. I've been involved with the web since the mid-90s (think blinking text, flaming skulls, etc.), and I took a bunch of courses in the Extension School before kids and career happened, but I really need to take a deep dive and get up to speed on modern web technologies and workflows. I also do some work in Drupal which runs on PHP, so this course should help in that regard as well.

Looking forward to the weeks ahead!

**Comment by kisa7081** [comment]
Hey, Daniel (Dan) McCullough here.  I'm a long time Java developer working for a government contractor with the USDA Forestry Service.  I'm working toward the Graduate Certificate in Web Technologies.  

Quick question: I previously used my "g.harvard.edu" email to join GitHub Education, but I never did receive a confirmation email from them.  And just now I did the same to join the Slack Chat, and have yet to receive an email from them.  Do outside messages sent to a "g.harvard.edu" account get blocked?

**Comment by susanBuck** [comment]
@kisa7081 Hm, that's odd. I've not (yet) heard of students having issues with g.harvard.edu addresses w/ Github or Slack.

Give your spam box a check (if you haven't already) - I noticed the other day that promo emails from Slack were getting caught there.

Can anyone else confirm/deny they've been able to sign up w/ g.harvard.edu?

**Comment by kisa7081** [comment]
Never mind, it seems maybe it's Canvas that doesn't display outside messages.  I can see everything now through Google Mail.

**Comment by gjrett** [comment]
Hi!

I'm Greg Retter, a Professional Electrical Engineer, and I've spent over 27 years specializing in automation and control, with some wide range of programming.  I'm pursuing the online Software Engineering Master's to learn more about AI, IIOT, and Big Data applications.

**Comment by liataun** [comment]
`Brian` here. My life consists of databases and what seems like perpetual Application Analyst/Tier III tech support roles, so I am hoping to expand my application programming skills, AI knowledge, and Web/Cloud experience.

I am taking this class as a `blend of building my confidence`, `developing skills for work` (we have a set of DB driven ETL web portals), and hopefully `getting a Master's degree`, though I haven't decided for sure if the HES Software Engineering focus is the right fit. I have a habit of long posts and over-thinking, but I love to share what I know, so `feel free to ask me questions if any of my posts interest you!`

**Comment by temmiezy** [comment]
Hi 
My name is Kenny and i'm a Software Engineer from Chicago. I have been a software developer for about 10 years using a variety of php frameworks except Laravel so i hope to learn a lot from this course and also complete the Masters degree program

**Comment by llandau** [comment]
Hello,

My name is Leo and I'm a Software Engineer from the SF Bay Area. I'm working towards the MLA degree in Software Engineering. I like being able to play around with technologies that I don't necessarily get to use in the office. Then sometimes I'm able to incorporate the use of these technologies into our production systems. That's pretty cool.

**Comment by cuneo24** [comment]
Hello everyone! My name is Mike and I am from Salisbury, MA. I currently work for Harvard Dining Services at Dunster House as a cook. What brought me to this course is further pursuit of my education with web technologies. I have a BS in IT from UMass Lowell, where I concentrated on web development and graphic design, but what I learned left me less than confident to enter the world of front-end web development upon graduation. This is my second semester with the Extension School and after the impression the Javascript course left me with, I look very forward to working with everyone this semester! My end goal is a certification in web technologies.

In the past I have worked with PHP using a GoDaddy server I had that ran cPanel and MySQL, and it seemed very straightforward at first with database information retrieval, but a few key things I look forward to learning about in this course are email creation, file uploading, and the logic behind creating a login system and users.

**Comment by NwlSmith** [comment]
Hi everyone!
My name is Nate and I am from Jamaica Plain, MA. I work at a place called Einstein's Workshop, a STEM education center for middle school aged students, where I teach a class on 3D printing. I am currently on a gap year as I transfer from one university to another, and in the meantime, I am taking courses to fulfill requirements and also courses that I think will be useful in the future. I am planning on entering a career in game design with a focus on programming, and I am currently developing a curriculum for a new course at my job on making games using Unity.

**Comment by dianebainbridge** [comment]
Hi,

I'm Diane.  I currently work as a web developer.  Our company recently started using PHP, previously we had used mostly .NET  I used PHP years ago to create an online soccer scheduling web site for our town but I thought it was time to update my skills and the tools I use so I decided to take this class.

**Comment by rdalby** [comment]
Hi,

I'm Rachel and I am from Swartz Creek, MI and just recently moved to New Hampshire. I work at Harvard School of Public Health as a Applications Programmer Analyst.  This is my first course with the extension school. I just want a refresher and that is why I'm taking this course.

**Comment by nathanielhunt** [comment]
Nathan here! I'm a lab manager at Harvard Psychology, where I do a lot of server admin and programming for online experiments. This course will be directly applicable to my job, but I'm also planning on pursuing the graduate degree in Software Engineering through the Extension School.

**Comment by contactjoehale** [comment]
Hey everyone,

Joey Hale here. I work as a software engineer at Careerbuilder. I've been there the past 5 years. Started off on a legacy PHP application built on symphony which has about 600k lines excluding external dependencies, so it's a behemoth. Moved from there to the search and recommendations team and most of our apps are node.js hosted and deployed in AWS. I'm looking to stay sharp in programming as its quick to fall behind. Im am most definitely NOT a front-end developer so this course is already proving difficult, haven't had touch much CSS/HTML since undergrad.
