### ISSUE TITLE
Domain won't see project 1

### ISSUE THREAD

**Issue by gjrett** [susanBuck/dwa15-spring2019#10]
Greg Retter - I went through all the homework and videos, and everything seems to have worked fine. I finished project 1, pushed it to GitHub, pulled it to my digital ocean server and saw the updated files in the /var/www/html directory, but my domain doesn't see them.  The domain sees the digital ocean and shows the basic index.html page, but I can't seem to get it to see the project index.php.  I've tried matching my droplet name to my domain, but that changed nothing.  My droplet is configured as the default, but it looks like it is not pointing to /var/www/html, which is where my files are located.  Is there a configuration file that need the /var/www/html path set, or did I somehow miss that part?

Thanks.

**Comment by susanBuck** [comment]
To help you debug, ca you share the following:

1. The full contents of your production server's virtual host file (`/etc/apache2/sites-enabled/000-default.conf`)
2. A screenshot of your DNS settings
3. The domain you're using

**Comment by llandau** [comment]
My understanding is that after following the instructions, the `domain` is *expected* to show the "basic index.html page" (or maybe the hello world page). The subdomain p1.`domain` is where the project will be. You should be able to check if `domain`/p1 is working to show the project 1 files. That should also work. Then if that's working you should be able to setup the subdomain per the instructions [here](https://github.com/susanBuck/dwa15-spring2019/blob/master/servers-and-git/production-domain.md#virtualhostsubdomain-setup)

**Comment by susanBuck** [comment]
@gjrett noted in Slack that he re-did the process and it's working now, so closing this issue.
