### ISSUE TITLE
No 'info.php' file in var/www/html

### ISSUE THREAD

**Issue by bibliodrone** [susanBuck/dwa15-spring2019#11]
Hi, 

I have completed the setup of the Droplet and establishing the RSA key for Digital Ocean <> Github, as described in "_Deploy to Production_", but have encountered a problem such that I don't see the expected ```info.php``` file:

> Your directory structure on DigitalOcean should now look like this:
> 
> /var/www/html
> - hello-world/
> - index.html
> - info.php

I do not see an ```info.php``` file in my listing. Is this a problem, and if so, what's the best way to solve it? Also, I named the repo folder ```hello-world_dwa``` because I already had a repo called ```hello-world``` on GitHub.

My listing:
> ```
> root@gw-dwa15:/var/www/html# ll
> total 20
> drwxrwxr-x 3 www-data www-data 4096 Feb 11 02:09 ./
> drwxrwxr-x 3 www-data www-data 4096 Jan 10 16:38 ../
> drwxr-xr-x 4 root     root     4096 Feb 11 02:09 hello-world_dwa/
> -rw-rw-r-- 1 www-data www-data 6541 Jan 10 16:38 index.html 
> ```

Thanks, 

Gerry Walden

**Comment by susanBuck** [comment]
Hi Gerry -

This is not a problem. The `info.php` file is one that used to come on DigitalOcean LAMP servers by default. It looks like they've removed it in recent updates.

I'll update the notes to reflect this. Sorry for any confusion!

If you're curious, the `info.php` file (when it existed) just contained the output of the php command `phpinfo()` which is described in this note set: [Php: Error reporting](https://github.com/susanBuck/dwa15-spring2019/blob/master/php/error-reporting-and-configs.md)
