### ISSUE TITLE
Window's users - which home directory shortcut works for you?

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2019#12]
Quick survey for the Window's students in the course...

1. In cmder, are you able to run `cd %home%` and navigate into your home directory? Or does it report back `The system cannot find the path specified.`?

2. What version of Windows are you using, and are you running cmder as an admin or normal user?

**Background**
I introduce the `%home%` shortcut in the notes on setting up SSH keys ([ref](https://github.com/susanBuck/dwa15-spring2019/blob/master/servers-and-git/github-setup.md#generate-ssh-keys-on-your-computer)), and a couple students reported in Slack that the shortcut wasn't working for them.

One student reported that using `%homepath%` instead worked for them, and [wikipedia confirms](https://en.wikipedia.org/wiki/Home_directory#Default_home_directory_per_operating_system) that this is (one of) the default shortcuts for your home directory on Windows.

But, cmder is [configured with the `%home%` shortcut](https://github.com/susanBuck/cmder/blob/master/vendor/init.bat#L376), so that should - in theory - work for everyone using cmder. 

I'm trying to figure out why that might not be and your reply to this survey will give some data to help with that.

In the meantime, I'll update the notes to use `%homepath%` as we know that works, regardless of any cmder shortcuts.

**Comment by phil-plencner-hl** [comment]
I'm running Windows 10 Pro. When I type in `cd %home%` in cmder, it takes me to my home directory. I believe I am running it as a normal user and not as an admin.

**Comment by liataun** [comment]
Windows 10 Pro 64-bit. User is an admin, but cmder might not be "As Administrator". `cd %home%` works for me, though I have a vague memory that there was one place where I ended up using `%homepath%`. I am working on an old laptop due to an OS failure on my desktop, so I may have a chance to retry our setup in a few days...

**Comment by bibliodrone** [comment]
Hi, 

The difference is only an issue if you switch between drives. 
I am running **Windows 10 Home**. 
Starting in my home directory on ```C:\```: 

```$ echo %home% ``` returns  ```C:\Users\Gerald``` (my username)'. 
```$ echo %homepath%``` returns ```\Users\Gerald```. So either works if i am in ```C:\```.

However, if I switch to my ```D:\``` drive and then try 
```$ cd  /D %homepath%```, it fails,  whereas 
```$ cd /D %home% ```, which contains the complete path, will take me back to ```C:\Users\Gerald``` as expected. 

-Gerry

**Comment by XLi-Sophia** [comment]
HI,
I am running Window 10 Home 64-bits. User is admin, but I don't think is the same on Cmder since I have to used elevate command to edit the hosts file.
When I type in cd %home% command in Cmder, it taken me back to my home directory. Although, this had took me a bit to get used to vs. ~ on Linux.

Xli

**Comment by dianebainbridge** [comment]
Both %home% and %homepath% work for me
![home-path](https://user-images.githubusercontent.com/47259490/52733913-ef1e1400-2f91-11e9-8c84-b24c83000ec2.JPG)

**Comment by susanBuck** [comment]
Thanks everyone who weighed in - helpful data. 

Based on your reports, and my own tests, it seems independent on whether Cmder is run as admin or not.

Interesting observation about the different drives, @bibliodrone - I'm pretty sure the students who reported the issue were just working on the c:\ drive though. 

So, no definitive conclusions yet as to the cause of the discrepancy - but at least we know %homepath% consistently works. Given that, I'll clear this issue out.
