### ISSUE TITLE
Mismatch in PHP class notes for string functions

### ISSUE THREAD

**Issue by liataun** [susanBuck/dwa15-spring2019#13]
The page on [Functions](https://github.com/susanBuck/dwa15-spring2019/blob/master/php/functions.md) appears to have a mismatch between the built-in function named `ltrim` and the definition listed for that function. The definition listed appears to be for regular full `trim`.

I started to see if I could create a pull request for this issue, but do not think I will have time before Wednesday to do that correctly. Still learning how the collaboration end of the Git/GitHub process works.

**Comment by susanBuck** [comment]
Thanks for the head's up @liataun - I'll get that corrected.
