### ISSUE TITLE
SSH - OK to re-use private key on multiple local machines?

### ISSUE THREAD

**Issue by mpswain** [susanBuck/dwa15-spring2019#14]
This week we learned how to set up a SSH key and put a copy of the public key `dwa.pub` on Github and on DigitalOcean. Our private key `dwa` remains on our local machine, which in my case is at home.

If I'm on another machine, for example at work, and I want to SSH into DigitalOcean, is it advisable to copy the same private key `dwa` from my home to my work machine? Or is it better to create a new, separate public/private key pair for use on each machine?

(I am aware that there are [extra steps required to install an additional public key](https://www.digitalocean.com/docs/droplets/how-to/add-ssh-keys/to-existing-droplet/) on an existing Droplet.

Thanks,

Michael :key:

**Comment by susanBuck** [comment]
It's more typical, and I'd say advisable, to create a separate key for the different machine.

I don't see any advantages to using the same key - the time it'd take you to transfer the key over to the second machine is a wash with the time it'd take to just generate a new key.

It can also be useful when looking at a server's list of `authorized_keys` to see which individual machines have access to that server.

That's my two cents. If we've got any sysadmin/security experts in the class, you're encouraged to weigh in!

**Comment by liataun** [comment]
While no expert, it is definitely the case that any duplication or moving of your private key opens it up to chances for it to get compromised. While probably not an issue for this class, it is often good to practice the "best practices" that you want to be in a habit of for normal working environments.

As an added recommendation, for using separate keys for different machines, it can aid in troubleshooting. Knowing which machine is, for instance, creating the commits that are messing with your line endings... that sort of thing is really helpful when things go wrong, and easy to dismiss during setup where it doesn't seem to matter.

**Comment by susanBuck** [comment]
Great point @liataun about the process of moving the key itself opens it up to getting compromised. 

One clarification about the commit history though - that will depend on your git configs and is independent of the ssh keys. 👍
