### ISSUE TITLE
Nano and cmder resizing

### ISSUE THREAD

**Issue by liataun** [susanBuck/dwa15-spring2019#16]
When working in `nano`, I found that *if I had a file open and resized the cmder window*, the rendering would freak out and become unreadable. I could still enter exit and process freeze commands, but it was disconcerting when editing Server side hosts files. Even after getting back to what seemed like the command line, the rendering of text in cmder was not behaving normally. In one case I accidentally paused the nano process while trying to get the behavior to stop and had to figure out how to end that session of nano, so that I could be sure of the state of the hosts file.

Does anyone know a clean way to reset the nano session regardless of save state, without needing to see the menu, the next time I do this by accident?

**Comment by susanBuck** [comment]
Would `ctrl+x` (Exit) + `n` (no, don't save changes) do what you're looking for?

**Comment by liataun** [comment]
I think those might, but is was difficult to see the prompts to know when to type. I will try to find a safe way to test.

**Comment by susanBuck** [comment]
The way I tested it was to just create a dummy text file to work with. With that I was able to reproduce the issue you described and successfully "abort" out of the file without any changes.

**Comment by liataun** [comment]
Thanks. This seems to work. I will try to be careful about stopping to think whether I need to close with saving or close without saving if I resize by habit in the future. The initial shock of not knowing what state the file would end up in was my biggest concern. It seems simply a display glitch, which is manageable.
