### ISSUE TITLE
PHPStorm configuration - running php files in the IDE

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#18]
I've installed *PHPstorm* and attempting to **run** a basic "Hello World" file within the app but I am **unsuccessful**.  I'm used to NetBeans IDE where you can run your files within the IDE and want to do the same in *PHPstorm* (so I can find a way to test code before moving to production).  Attached are some screen-shots.

If I can't get *PHPstorm* to run files is it ok if I use *NetBeans*?

[PHPstorm-config.docx](https://github.com/susanBuck/dwa15-spring2019/files/2867176/PHPstorm-config.docx)

**Comment by bret-blackford** [comment]
Ok, found some php.exe configuration info here … https://medium.com/@zacbanas27/a-quick-guide-to-configuring-php-on-phpstorm-35aa163048e4  and seems like this may help.

**Comment by susanBuck** [comment]
Good find, @bret-blackford. I don't typically run my php files directly in phpstorm, so I can't speak directly to this, but report back if you have any issues with that setup and I can run through it on my end to help troubleshoot.

**Comment by XLi-Sophia** [comment]
Thanks for sharing the configuration info Bret. I'd followed the guide and successfully setup Project 1 to be run within the PhpStorm IDE. 
However, it took me a little bit to found how to bring up the CLI Interpreter window. I think fellow below steps it would help other who wish to do the same a little bit easier. Hope it help.

Existing Project:
File >  Settings... > Languages & Frameworks > PHP > continue above given guide

Future New Project:
File > Settings for New Projects > Languages & Frameworks > PHP > continue above given guide

**Comment by temmiezy** [comment]
thanks for sharing Bret

**Comment by nathanielhunt** [comment]
In case anyone was just looking for a place for interactive PHP, I was able to get to a PHP REPL with `php -a`. And there are a number of more fully-featured REPLs if you do some searching.

**Comment by susanBuck** [comment]
@nathanielhunt Good tip! Also, fyi, when we get to Laravel, it has a [built in REPL called tinker](https://laravel.com/docs/5.7/artisan#tinker).

**Comment by tachyon99dwa15** [comment]
I tried to do File->Import Settings and it said the file is not in zip format? The file is in jar. I've been struggling to get it to input the jar file. Any suggestions?
