### ISSUE TITLE
PSR-1 2.3 ("Side Effects")

### ISSUE THREAD

**Issue by tealuxe** [susanBuck/dwa15-spring2019#19]
I understand the principle involved here, but it seems a bit strict the way they have worded it. I would think that declaring new symbols could conceivably be part of reasonable procedural code that has such "side effects." It also seems a bit restrictive toward a web-programming mindset, no?

Could we possibly look at an example or two of how this is relevant for the specific material we are reviewing?

**Comment by susanBuck** [comment]
There's a [good post on StackOverflow](https://stackoverflow.com/questions/13298795/psr-1-2-3-side-effects-rule/13299008) relevant to this, with an answer from one of the FIG contributors. One of the things he says is this:

>> "Lastly... don't adopt PSR-1 for the sake of. If you have a valid reason to not follow the rules in certain spots, break the rules. They're not laws. Common sense reigns supreme."

With that in mind, there are aspects of this rule I would support bending. For example, I'm bending that rule by invoking `session_start` here in foobooks0 -> [logic.php :: line 8](https://github.com/susanBuck/foobooks0/blob/master/logic.php#L8)

I would not bend the rule of declaring new symbols, though. If you've got a specific scenario in mind where you think it might be reasonable, we can discuss some more.

>> It also seems a bit restrictive toward a web-programming mindset, no?

PHP is primarily a web-programming language, and the FIG (Framework Interoperability Group) consists of developers working with web frameworks. If you're using PHP for other types of programming, the FIG guidelines may not be the best guide.

>> Could we possibly look at an example or two of how this is relevant for the specific material we are reviewing?

For our purposes, and the aspect I think is most important, we can narrow down this rule to the following:
+ Don't produce any output/display in your logic files (i.e. nothing that prints to the page)
+ Don't use non-display specific logic in your display files (i.e. don't define variables, functions, etc.)

For some examples...
In [foobooks0 search.php](https://github.com/susanBuck/foobooks0/blob/master/search.php) we see all the logic work being done. Data is retrieved from the session; variables are set; the "search" algorithm is run. No output is produced to the page.

In [foobooks0 index.php](https://github.com/susanBuck/foobooks0/blob/master/index.php) we see all the display work being done. This includes some display-specific logic such as determining whether something should be printed:

```php
<?php if (isset($searchTerm)): ?>
```

Or iterating through what should be printed:

```php
<?php foreach ($books as $title => $book): ?>
```

But no where are we, for example, defining what $books is, or how the search works, etc.
