### ISSUE TITLE
Table of Content links confusion

### ISSUE THREAD

**Issue by liataun** [susanBuck/dwa15-spring2019#24]
It looks like the `README.md` Contents for class notes has a link for *Deployment script*, but it links to a 404 page. My guess is we are not meant to see this yet?

I discovered this while looking for this week's pages on *Object Oriented Programming*, *Validation*, and *Using Form.php*. I did not find them, but I am not sure if I should be expecting to?

**Comment by susanBuck** [comment]
Apologies, it looks like I had committed the changes to the table of contents for Week 4's material but failed to push them. Corrected now. And yes, Deployment script material is coming up later in the semester - link should not have been there.
