### ISSUE TITLE
form.php

### ISSUE THREAD

**Issue by iamwenz** [susanBuck/dwa15-spring2019#25]
Hi there, hope everything is well. 
SoI've been trying to fix my code from form.php but it didnt seems to work at all. 
so i submitted to the working codes without the class first (the codes are working : https://github.com/iamwenz/p2 ), but I'm still trying to figure out what went wrong with my class form. 
anyone can kindly tell me what might went wrong ? 

thanks, chiwen. 

```php
<?php

class Form {

private name;
private gender;
private weight;
private height;
private age;

public function __construct(string $name, string $gender, string $weight, string $height, string $age) {
$this->name = $_POST['name'] ?? '0';
$this->gender = $_POST['gender'] ?? '0';
$this->weight = $_POST['weight'] ?? '0';
$this->height = $_POST['height'] ?? '0';
$this->age = $_POST['age'] ?? '0';
}

public function getBMR() {
if($this->gender == "Male"){
return 88.362 + (13.75 * $this->weight) + (5.003 * $this->height) - (5.677 * $this->age);
} else {
return 447.593 + (9.247 * $this->weight) + (3.098 * $this->height) - (4.330 * $this->age);
}
}
}
```

**Comment by susanBuck** [comment]
When you say it didn't work at all - can you be more specific - did you get any errors? If so, what did the errors say?

Also, can you share the code you used to attempt to use this class (I don't see any in your repo).

**Comment by susanBuck** [comment]
Side note: Following the instructions in the post [Example post demonstrating markdown features](https://github.com/susanBuck/dwa15-spring2019/issues/2) I reformatted your original post so it was more legible.

Please follow these instructions for all future posts so we can more efficiently read your question and help you out. : )

**Comment by susanBuck** [comment]
Student confirmed via email they had resolved the issue so closing this thread.

But, for anyone else reading this - looking closer at the code, one problem I see is the class properties are missing the dollar sign syntax.

e.g.
```php
private name;
```
 
should be:
```php
private $name;
```

Once that's fixed, I was able to successfully test/utilize the class:

```php
if ($_POST) {
    $form = new Form($_POST["name"], $_POST["gender"], $_POST["weight"], $_POST["height"], $_POST["age"]);
    $bmr = $form->getBmr();
}
```
