### ISSUE TITLE
WEEK 6 Notes

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#26]
### All the behind the scenes administrative programming tasks discussed this week are overwhelming so I needed to keep the following summary in mind while reading and viewing the lectures: ###

**Composer** = A dependency manager program for PHP (includes autoloading)
**Artisan** = a PHP command line tool that ships with Laravel and provides shortcuts and utilities for working with your application.  ***tinker*** is an Artisan command which lets you test code via the command line.  ***tinker*** examples:
- php artisan route:list
- php artisan make:controller
- php artisan tinker (*in command line, within project directory*)

**routes** = a way to ensure all URLs go thru index.php
**facades** = a "static alias" to an underlying class/object in Laravel
**Controllers** = classes used to group related request handling logic (created manually or via Artisan). Provide a way to organize an application into logical parts.  Example:
``` php
Route::get(`/books', 'BookController@index');
```
``` php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
class BookController extends Controller {
    /**
    * GET /books
    */
    public function index() {
        # Work that was previously happening in th eroutes file is now happening here
        return 'Here are all the books ...';
    }
}
```
**routes -> controllers** = set up routes so they invoke an "*action*" instead of a *closure*.
**"action"** = method in a controller invoked from routes via *Controller@method* e.g., *BookController@index*
**closure** = anonymous functions, also known as closures, allow the creation of functions which have no specified name.
**namespace** = helps prevent name collisions and performs autloading

**Comment by susanBuck** [comment]
Good summary, thanks for sharing. Closing this out since I just posted Week 7 material. : )
