### ISSUE TITLE
error adding first view

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#31]
Attached is an error I receive when stubbing up my first view - "invalid argument exception"
Looking for assistance in debugging.  My code is in GitHub here … https://github.com/bret-blackford/BMI-Laravel

**Comment by susanBuck** [comment]
Hi @bret-blackford - 

`InvalidArgumentException` is the type of exception. To help troubleshoot this, it's helpful to have more details about the error, which in this case is `View [bmi.bmi] not found.`

![image](https://user-images.githubusercontent.com/237711/54850164-beca4380-4cbc-11e9-93d7-17ec224d9ec4.png)

Furthermore, when we drill down the error it's coming from this line:

![image](https://user-images.githubusercontent.com/237711/54850213-e8836a80-4cbc-11e9-9923-e40801ec3680.png)

The line in question:

```php
return view('bmi.bmi')->with(['title' => $title]);
```

The syntax you're using there to return the view looks correct, so the next step is to double check the name of the view file itself which is just [`bmi.blade`](https://github.com/bret-blackford/BMI-Laravel/blob/master/resources/views/bmi/bmi.blade).

Compare that to your existing view file (`welcome.blade.php`) and you should be able to spot the issue.

**Comment by bret-blackford** [comment]
Yep!  I didn't have the .php at the end of my file (assuming it would be added by the IDE).  **Now works!!** (ref http://www.bret-dwa15.vip/BMI-Laravel/public/calc ) 

**An additional question, though** --- the blade view is pulling in the default value.  How do I pass in a string (like a book title) at the URL and get it to display in the view?  Seems like a routes kinda thing but I don't see the issue there ???

**Comment by susanBuck** [comment]
You'll want to set up a route parameter on your route, e.g.:

```php
Route::get('/calc/{$title?}', 'BMIController@calc');
```

(Of course $title isn't applicable in the case of BMI, but sticking with your example)

You can read more about that here:
<https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/routes.md#route-parameters>

**Comment by bret-blackford** [comment]
**Susan, THANK YOU !!**  Thinks now seem to be working as intended.
Also, thanks for the link as your example is a bit off - no need for leading $ in {$title?}. Below seems to work ...
``` php
Route::get('/calc/{title?}', 'BMIController@calc');
```

Ah!  Now I can better enjoy the weekend.  You do the same, Susan, and again, I really appreciate the information and the quick response to my questions.

**Comment by susanBuck** [comment]
np! 

And good catch on the unnecessary `$`.  I put it there out of force of habit with variables. : )
