### ISSUE TITLE
Pass multiple parameters to Controllers and views

### ISSUE THREAD

**Issue by bibliodrone** [susanBuck/dwa15-spring2019#34]
To use the _foobooks_ code as a starting point, what would be the proper means of altering it to pass multiple parameters, e.g. **title1** and **title2**?  

I've altered the snippet from `BookController.php` below to illustrate what I am getting at--what is the correct way to do this so that it would map to the GET request as entered in the browser address bar , e.g. `http://books.loc?title1&title2`

```
/**
* GET /books/{title1, title2}
*/
public function show($title1, $title2)
{
    return view('books.show')->with(['title1' => $title1, 'title2'=>$title2]);
}
```

Thanks, 
Gerry

**Comment by susanBuck** [comment]
You can set up multiple parameters on a route like this:
```php
Route::get('/books/{title1}/{title2}`, `BookController@show`);
```

```php
/**
* GET /books/{title1}/{title2}
*/
public function show($title1, $title2)
{
    return view('books.show')->with(['title1' => $title1, 'title2' => $title2]);
}
```

Here's another example from the docs at <https://laravel.com/docs/5.8/routing#route-parameters>:

![image](https://user-images.githubusercontent.com/237711/55016798-dc9dee00-4fc5-11e9-90f9-7924637618cb.png)

**Comment by bibliodrone** [comment]
So, in the case of the path
**Route::get('/books/{title1}/{title2}`, `BookController@show`);**

you can pass multiple parameters within brackets, separated by '/'. So therefore, it sounds as though the '/''s between the **{title1}** and **{title2}** don't imply a path hierarchy, as they would in a URL such as:
**foobooks.me/books/title1/title2/**

Is that correct? 

Thanks for your help, 

Gerry

**Comment by susanBuck** [comment]
>> you can pass multiple parameters within brackets, separated by '/'

That is correct!

>> the '/' between the {title1} and {title2} doesn't imply a path hierarchy

Correct - It does not imply a typical directory path hierarchy as we're used to with websites that are not using a routing system.

For a refresher on this, we can look back at the [Basic flow](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/basic-flow.md#basic-flow) notes which state:

>> Throw away this traditional “URL maps to specific file” thinking. Modern web frameworks use something called routing.

**Comment by bibliodrone** [comment]
OK, thank you for clarifying that. I did read the notes, (I promise!) but I am just very accustomed to seeing those symbols in a certain way. Now it is clear, thank you!

-Gerry

**Comment by susanBuck** [comment]
You're welcome! And it never hurts to reiterate the notes as a refresher. : )
