### ISSUE TITLE
view error - htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#35]
My code is in GitHub at https://github.com/bret-blackford/BMI-Laravel

At this point I am just trying to get my view with associated form to display.  I'm getting an error about 'String' vs 'Array' parameters?  Project can by called via http://bmi-laravel.bret-dwa15.vip/calc or http://bmi-laravel.bret-dwa15.vip/ 

http://bmi-laravel.bret-dwa15.vip/calc  throws this error ...
```

(2/2)   ErrorException  htmlspecialchars() expects parameter 1 to be string, array given (View: /var/www/html/BMI-Laravel/resources/views/bmi/show.blade.php) --
```
and 
http://bmi-laravel.bret-dwa15.vip/  throws this error …
```
(2/2)    ErrorException  htmlspecialchars() expects parameter 1 to be string, array given (View: /var/www/html/BMI-Laravel/resources/views/bmi/bmi.blade.php)
--
```

**Comment by susanBuck** [comment]
Hi Bret -

The specific line the error is being triggered from is this:

```php
<input type="date" name='dob' value=' {{ old($dob) }} '>
```

What the `old` helper method expects is some *key* for data you're trying to retrieve from the session. 

I suspect you probably meant to specify the key of `dob`, not the actual variable of `$dob`:

```php
<input type="date" name='dob' value=' {{ old("dob") }} '>
```

For reference:
![image](https://user-images.githubusercontent.com/237711/55422149-fd77bd80-5548-11e9-9fc5-e23b02d184be.png)

**Comment by bret-blackford** [comment]
I'm now getting stuck here due to adding validation …
```

(1/1) ErrorException Declaration of App\Http\Controllers\BMIController::validate(Illuminate\Http\Request $request) should be compatible with App\Http\Controllers\Controller::validate(Illuminate\Http\Request $request, array $rules, array $messages = Array, array $customAttributes = Array)
--
in BMIController.php line 9

```
Can see error here - http://bmi-laravel.bret-dwa15.vip/

**Comment by bibliodrone** [comment]
Could there be a problem with how the arguments are being passed to the method?

Cutting down to the end of the paths mentioned in the error message, it seems to be saying that it is seeing:

`Request $request`

...whereas it is expecting additional arguments:

`Request $request, array $rules, array $messages = Array, array $customAttributes = Array`

-Gerry

**Comment by susanBuck** [comment]
@bret-blackford - You're getting this error because you've created a method called `validate` within your BMIController, which is a method name already used by Laravel's Controller class.

To fix, name your `validate` method something else.


To understand the error:
```
Declaration of App\Http\Controllers\BMIController::validate(Illuminate\Http\Request $request) should be compatible with App\Http\Controllers\Controller::validate(Illuminate\Http\Request $request, array $rules, array $messages = Array, array $customAttributes = Array)
```

Here's what's going on:

Your BMIController.php inherits functionality from some core classes within Laravel. 

Within one of these inherited classes, it's defined that a `validate` method *must* accept a certain set of parameters (`Illuminate\Http\Request $request, array $rules, array $messages = Array, array $customAttributes = Array`)

When you define your own `validate` method in the child class and set it to have different parameters (`Request $request`), it breaks this rule, and the error is created.

Hope that helps understand what's going on! Overwriting default/build-in method names is always a weird little gotcha that can be tricky to understand.

**Comment by bret-blackford** [comment]
on to a new error.  When I click the [calculate] button the flow should be re-directed to my BMIController::chex() method.  Instead, I get a **419 page expired** error

Can see error here - http://bmi-laravel.bret-dwa15.vip/
My code is in GitHub at https://github.com/bret-blackford/BMI-Laravel

**Comment by susanBuck** [comment]
In my book, a different error is still progress. : )

You're getting the new 419 page expired error because you're submitting your form via POST but don't have a CSRF field.

For a refresher on this, reference: [CSRF Protection in Laravel](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/forms-post.md#csrf-protection-in-laravel)

**Comment by bret-blackford** [comment]
**Bingo !**   
Yep, that fixed it.  Now I'll move on to breaking other things.  Thanks!

**Comment by susanBuck** [comment]
Excellent! I'm on Slack now if you want any live help with breaking things. : )

**Comment by bret-blackford** [comment]
In my code I use radio buttons and selectors for a few items.  How do I use the Laravel features to allow me to display what was previously selected (as I've done below with "dob")?

```php
<label class='line'>Date of Birth</label>
        <input type="date" name='dob' value=' {{ old("dob") }} '>

        <div id='gender-block'>
            Gender:
            <input type="radio" name='gender' value='Male' >
            <label>male</label>
            <input type="radio" name='gender' value='Female' >
            <label>female</label>
        </div>
        <div id='height-block'>
            <label>Height in feet
                <select name="heightFeet" >
                    <option value="1" >1</option>
                    <option value="2" >2</option>
                    <option value="3" >3</option>
                    <option value="4" >4</option>
                    <option value="5" >5</option>
                    <option value="6" >6</option>
                    <option value="7" >7</option>
                    <option value="8" >8</option>
                </select>
            </label>
```

**Comment by susanBuck** [comment]
For an example of this, think back to the form examples we saw when working with plain PHP, [for example](https://github.com/susanBuck/dwa15-php/blob/master/forms-inputs/dropdown.php):

```html
<select name='day' id='day'>
        <option value='choose'>Choose one...</option>
        <option value='mon' <?php if ($day == 'mon') echo 'selected' ?>>Monday</option>
        <option value='tue' <?php if ($day == 'tue') echo 'selected' ?>>Tuesday</option>
        <option value='wed' <?php if ($day == 'wed') echo 'selected' ?>>Wednesday</option>
        <option value='thu' <?php if ($day == 'thu') echo 'selected' ?>>Thursday</option>
        <option value='fri' <?php if ($day == 'fri') echo 'selected' ?>>Friday</option>
    </select>
```

This shows how we use PHP code to check if the value for `$day` matches the given option's value, and if so, "selected" is echo'd.

Taking this example, and applying what we know about Blade and ternary operators, we could re-write each option in our view to something like this:

```html
<option value='mon' {{ (old('day') == 'mon') ? 'selected' : '' }}>Monday</option>
```

**Comment by susanBuck** [comment]
(FYI - These follow-up questions would all make good independent posts - because other students might have similar questions and might not find the details if they're buried in this thread.)
