### ISSUE TITLE
redirecting

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#38]
I've completed processing my form in the BMIController.checx() method and want to send result back to my index page.  I am trying the following with no success.

```php
        $response = $name . ", you are a " . $age . " year old " . $gender;
        $response .= " and have a body mass index (BMI) of : <b>" . $bmi . "</b>%";
        $response .= " which classifies you as <b>" . $status . "</b>";

        return redirect('/bmi')->with([
            'response' => $response
        ]);

        //return view('/bmi')->with([
        //    'response' => $response
        //]);
```
I've tried to follow instructions at https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/forms-get.md 

My code is in GitHub here - https://github.com/bret-blackford/BMI-Laravel

**Comment by bret-blackford** [comment]
and when do you use **return redirect('/book/search')** and when do you use **return view('book/search')** ?

**Comment by susanBuck** [comment]
You're redirecting to `/bmi` and passing with it a value for `response`. 

**But where/how are you retrieving the `response` and trying to use it?**

If we look at `BMIController@index` (the method invoked by `/bmi`) we see this:

```php
 public function index() {
        //dump('in app/Http/Controllers/BMIController::index() - just prep');
        return view('bmi.bmi')->with([
                    //return view('bmi.show')->with([
                    'name' => null,
                    'dob' => null,
                    'gender' => null,
                    'heightFeet' => null,
                    'heightInches' => null,
                    'weight' => null,
        ]);
    }
```

Note how nothing in this method is trying to extract the `response` from the session.

Contrast that to the example (ref: [Show the form, post-processing](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/forms-get.md#show-the-form-post-processing)) where the data (in this case, `searchTerm`, `caseSensitive`, `searchResults`) passed as part of the redirect is extracted from the session and passed to the view for display:

```php
public function search(Request $request)
{
    return view('books.search')->with([
        'searchTerm' => $request->session()->get('searchTerm', ''),
        'caseSensitive' => $request->session()->get('caseSensitive', false),
        'searchResults' => $request->session()->get('searchResults', []),
    ]);
}
```

**Re: when to use `redirect()` vs `return view()`**

In the examples, I used `return redirect` in the "processing" methods, like performing the search, or adding the book (eventually). It does the processing, then redirects the user to wherever you want to display the results.

I used `return view` in the "show" methods, e.g. the method that shows the form to perform a search, or shows the form to add a book.

**Comment by bret-blackford** [comment]
Agh!!  I'm now getting this …
```php

(2/2) ErrorException Undefined variable: response (View: /var/www/html/BMI-Laravel/resources/views/bmi/bmi.blade.php)
--
in da54caa4b9c25184ec2affee37ad6b6c2792adc0.php line 72
```

**Comment by susanBuck** [comment]
```
public function index(Request $request) {
        $response = $request->session()->get('response', null);

        return view('bmi.bmi')->with([
                    //return view('bmi.show')->with([
                    'name' => null,
                    'dob' => null,
                    'gender' => null,
                    'heightFeet' => null,
                    'heightInches' => null,
                    'weight' => null,
        ]);
    }
```

You are now successfully extracting the response from the session and storing it in a variable called `$response`, but you're not actually making it available to the view. You need to include it as part of the data array being sent to the view via the `with` method. E.g.:

```php
return view('bmi.bmi')->with([
                    'name' => null,
                    'dob' => null,
                    'gender' => null,
                    'heightFeet' => null,
                    'heightInches' => null,
                    'weight' => null,
                   'response' => $response, # <-- NEW
        ]);
```


As a side note, you should not be building your entire response message in the controller method like you're doing:

```php
$response = $name . ", you are a " . $age . " year old " . $gender;
$response .= " and have a body mass index (BMI) of : <b>" . $bmi . "</b>%";
$response .= " which classifies you as <b>" . $status . "</b>";
```

This is display code and should be happening in the view. Rather than constructing the entire message in your controller, you should just send back the data necessary to construct the message in the view (`bmi`).

You don't have to worry about refactoring this now - focus on just getting it working. I just wanted to mention this in case other students are looking at this for an example.

**Comment by bret-blackford** [comment]
(so many questions … )  Well, I understand what you mention above and it did enable me to get the result back to the main page.  **But original results are gone**.  So, old() no longer works and we need to find another way to maintain form state?

**Comment by susanBuck** [comment]
Check out the note at the bottom of [this page](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/validation.md#retaining-old-form-data):

>> Note that the form’s values are only accessible via old if it’s the validation method that is initiating the redirect (as a result of failed validation).

>> If you do your own redirect and wish to take advantage of the old method, you have to include a withInput method as part of your redirect, e.g.:
```php
return redirect('/books/create')->withInput();
```

In your case, it would look like this:

```php
return redirect('/bmi')->with([
    'response' => $response,
])->withInput();
```

That should do the trick if I'm understanding the problem correctly (if not, let me know!)

**Comment by bret-blackford** [comment]
Thanks for your patience and assistance.  Now to move on to the refactoring and cleaning things up.
