### ISSUE TITLE
server alias

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#39]
This was probably discussed but I just found out you can make an alias to your web application using the **/etc/apache2/sites-enabled/000-default.conf** file.  
Originally I thought you needed to use the exact name of the php project, and would create projects name "P1" or "P2" as per class url expectations.  For P3 I started my project name "BMI-Laravel" and was testing using http://BMI-Laravel.bret-dwa15.vip.   That url did not meet class requirements which expects http://p3.bret-dwa15.vip so I thought I either needed to 1) create a new project named "P3", 2) rename my current project to "p3", or 3) keep my project named as is and find an alias (preferred option).
Fortunately after modifying the **/etc/apache2/sites-enabled/000-default.conf** file as noted below I was quite happy to find that aliasing works !!

Others may not be as thrilled with this info as I am but I thought I would share (as the other options would be more work and prone to errors).

```
<VirtualHost *:80>
        ServerName BMI-Laravel.bret-dwa15.vip
        DocumentRoot "/var/www/html/BMI-Laravel/public"
        <Directory "/var/www/html/BMI-Laravel/public">
                AllowOverride All
        </Directory>
</VirtualHost>


<VirtualHost *:80>
        ServerName p3.bret-dwa15.vip
        DocumentRoot "/var/www/html/BMI-Laravel/public"
        <Directory "/var/www/html/BMI-Laravel/public">
                AllowOverride All
        </Directory>
</VirtualHost>
```

**Comment by liataun** [comment]
I have something similar setup for my foobooks application. I have two repositories for the foobooks examples we go over in the homeworks. The one I put up on the server has an added string in the project folder name, but I mapped it to the same URL as Susan is using in the homework. I keep having trouble with my attempts at copy/paste in the server, but aside from that I really like working with the alias functionality.

**Comment by susanBuck** [comment]
👍That's correct - the `ServerName` does not have to be the same as the `DocumentRoot`/`Directory` name.
