### ISSUE TITLE
`ll` command line alias

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2019#4]
Hi everyone -

I wanted to draw your attention to a command line alias you'll see me using frequently in lectures, which is `ll`:

![image](https://user-images.githubusercontent.com/237711/52144516-86977480-262c-11e9-88fb-a163b3324ff4.png)

This `ll` command is an alias I've set up that translates to `ls -la`:

![image](https://user-images.githubusercontent.com/237711/52144195-9bbfd380-262b-11e9-8c0a-b68234b8260f.png)
_(breakdown from [explainshell.com](https://explainshell.com/explain?cmd=ls+-la))_

In summary, `ls -la` will list the contents of a directory in long firm (i.e. with all the permission, ownership, date, etc. details), and it will also include hidden files. This is a really common/useful way to explore the contents of a directory.

If you went through the [Mac Terminal notes](https://github.com/susanBuck/dwa15-spring2019/blob/master/command-line/mac-terminal.md), I talk about this command in the [section on aliases](https://github.com/susanBuck/dwa15-spring2019/blob/master/command-line/mac-terminal.md#aliases), and if you customize terminal like I describe, you'll have access to this command.

For Windows/Cmder users, the command comes pre-setup for you in the build of Cmder I provide, so you'll also have access to it.

And finally, once we set up our production servers, you'll see it works there too (it's a common alias that many developers use, so our servers set it up by default).

**Anyone else have any favorite aliases that they recommend?**

**Comment by liataun** [comment]
I have no aliases as I am not familiar with their creation, but had been wondering if `ll` in the lecture was related to `ls -l`, so this is helpful. (I always forget how to type the -l option.)

**Comment by temmiezy** [comment]
'll' alias is a game changer. Wont understand till you have to use a colleagues work station who doesn't have it setup

**Comment by llandau** [comment]
> Anyone else have any favorite aliases that they recommend?

I like to create an alias to open up multiple applications or files at the same time. The following commands can be concatenated into an alias with the `&&` operator.

```
open /Applications/PhpStorm.app
open https://dwa15.com
open /Applications/MAMP/MAMP.app
cd /Users/leo_landau/Documents/harvard/cs15/workspace/localhost 
```

```
alias harvard='open /Applications/PhpStorm.app && open https://dwa15.com && open /Applications/MAMP/MAMP.app && cd /Users/leo_landau/Documents/harvard/cs15/workspace/localhost'
```
