### ISSUE TITLE
One more redirect question -- return redirect ->withInput() and with a value

### ISSUE THREAD

**Issue by bibliodrone** [susanBuck/dwa15-spring2019#42]
Is it possible to somehow do something like (this doesn't work as written)

 `return redirect('/showResults')->with(['returnMessage' => $returnMessage], withInput());`

that is, combine `withInput()` and `with([])` into a single returnable object of some kind to use in a redirect command? I recall the use of `dump($request)` in **books/search-process** to illustrate a number of methods and properties.

I am trying to preserve data for the redirect using the '**old**' function, but I also have another variable I would like to pass along on that redirect, as well.  Could I use the **$request** object for this? 

Thanks, 

Gerry

**Comment by susanBuck** [comment]
Hi Gerry -

Yes, the `with` and `withInput` method can be chained together. Here's the syntax you're looking for:

```php
return redirect('/showResults')->with(['returnMessage' => $returnMessage])->withInput();
```

**Comment by bibliodrone** [comment]
I see, thank you!

In general is it correct as a rule of thumb that the '`=>`' symbol is used in a somewhat equivalent manner to how the '`:`' is used in languages such as Python or Javascript; whereas the '`->`' is similar to the '`.`' 

 e.g.:  `return redirect("...").with( {"returnMessage" : returnMessage}).withInput() ;`

...and **PHP** is closer in syntax to a language like '**R**', I guess, though I am not as experienced with that language so maybe that is an over-generalization.

**Comment by susanBuck** [comment]
>> In general is it correct as a rule of thumb that the '=>' symbol is used in a somewhat equivalent manner to how the ':' is used in languages such as Python or Javascript; whereas the '->' is similar to the '.'

Yup, that's correct!

`->` is PHP's "object operator" and it's used to access methods and properties of an object.

`=>` is PHP's "double arrow operator" and is used as an access mechanism for arrays.

**Comment by bibliodrone** [comment]
I don't know why that didn't quite sink in before, but now I see. Thank you.
