### ISSUE TITLE
creating a table via migration

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#47]
I've attempted to create the foobooks table via migration but get some unknown table fields ???
![image](https://user-images.githubusercontent.com/11459198/56463946-20f19380-63a4-11e9-8741-891559b15594.png)

my code is here on GitHub ... https://github.com/bret-blackford/foobooks

**Comment by bret-blackford** [comment]
well ... re-read notes and **THIS IS IMPORTANT !!**
in XAMPP you must modify the `/apps/Providers/AppServiceProvider.php` file to limit string length.  As always, no shortcuts when programming.

**Comment by bret-blackford** [comment]
( slow progress but progress )

**Comment by susanBuck** [comment]
Glad you got it sorted out!

Anyone else having a similar issue - here's the relevant part of the notes:

[Important configuration preface for XAMPP users](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/db-migrations.md#important-configuration-preface-for-xampp-users)

And you can see it in action in [this video](https://www.youtube.com/embed/Jx6CUhgcOsA?rel=0&showinfo=0) at about the 3:15 mark.
