### ISSUE TITLE
Production Subdomain - 500 server error

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#49]
I'm having trouble getting my test P4 project loading in PROD.  I'm able to do basic testing on my local environment and have loaded this test code to DigitalOcean and modified the `/etc/apache2/sites-enabled\000-default.conf` files as noted below.  Then ran `service apache2 restart`, but still get a 500 error when attempting to access http://p4.bret-dwa15.vip 

Associated code in github here ... https://github.com/bret-blackford/Patient_Lab_Data 

Any ideas of what to try?

```

<VirtualHost *:80>
        ServerName p4.bret-dwa15.vip
        DocumentRoot "/var/www/html/Patient_Lab_Data/public"
        <Directory "/var/www/html/Patient_Lab_Data/public">
                AllowOverride All
        </Directory>
</VirtualHost>

<VirtualHost *:80>
        ServerName foolabs.bret-dwa15.vip
        DocumentRoot "/var/www/html/Patient_Lab_Data/public"
        <Directory "/var/www/html/Patient_Lab_Data/public">
                AllowOverride All
        </Directory>
</VirtualHost>
```
Here are the files in my prod environment ...
![image](https://user-images.githubusercontent.com/11459198/56871944-08f3c280-69e9-11e9-941e-0209808d3396.png)

**Comment by susanBuck** [comment]
I don't see a `vendor` directory in your project. Can you confirm you've run `composer install --no-dev` on production? (ref: [Build vendor directory](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/deploy-to-digital-ocean.md#build-vendor-directory))

I also don't see a `.env` file. (ref: [Environment file .env on production](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/deploy-to-digital-ocean.md#environment-file-env-on-production)).

While we're double checking the "set up on production" steps, also make sure you've [set the application key](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/deploy-to-digital-ocean.md#app_key).

Finally, if you're still getting a 500 server error, check the log files listed in the [troubleshooting section](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/deploy-to-digital-ocean.md#troubleshooting) of the notes and report back on any errors logged there.

**Comment by bret-blackford** [comment]
**That helped**!  I thought I had most of the steps associated with a new project summarized here ... https://github.com/bret-blackford/BMI-Laravel/blob/master/laravel-proces.md
I've clearly missed some crucial steps, and will fill in these blanks.  

Anyway, can now see application at http://p4.bret-dwa15.vip/debug and http://p4.bret-dwa15.vip/get , but I need to work on http://p4.bret-dwa15.vip (not sure why this isn't working in PROD but is in DEV)

**Comment by susanBuck** [comment]
re: http://p4.bret-dwa15.vip not working - whenever you see a 500 server error on production, check your `/storage/logs/laravel.log` for clues 👍

**Comment by bret-blackford** [comment]
I do not see a "laravel.log"

![image](https://user-images.githubusercontent.com/11459198/57201099-b3c02f80-6f59-11e9-90f4-f6587f6d207a.png)
.
![image](https://user-images.githubusercontent.com/11459198/57201108-e0744700-6f59-11e9-99ea-a9a411715f69.png)

**Comment by susanBuck** [comment]
Hi Bret - Thanks for the screenshots - very helpful. Looking at the first one, it appears the logs directory is still owned by `root`, not `www-data` which is why no log files are appearing - the permissions are not correct and the app can't write to that directory.

[Here are the relevant instructions on correcting the permissions...](https://github.com/susanBuck/dwa15-spring2019/blob/master/laravel/deploy-to-digital-ocean.md#permissions)

Once you fix that, try loading `http://foolabs.bret-dwa15.vip/` again - it should generate an error and write the details to the log file.

**Comment by bret-blackford** [comment]
Did the following in my PROD project folder ...
```chown -R www-data storage```
```chown -R www-data bootstrap/cache```
```ervice apache2 restart```

And **All Seems To Work !!**

I can now see my draft project at 
+ http://foolabs.bret-dwa15.vip
+ http://p4.bret-dwa15.vip

**Comment by susanBuck** [comment]
Excellent!
