### ISSUE TITLE
Week 13: increments/bigIncrements "Cannot add foreign key constraint" error

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2019#51]
In this week's (13) videos I introduce database table relationships.

As part of this process, I show how you can add columns to your tables that act as foreign keys to connect rows in that table to rows in some other table via the `id` field.

When creating the foreign keys in the [Part 5 video](https://www.youtube.com/embed/wA_yZJzUB3U?rel=0&showinfo=0) at about the 10:25 mark, I discover a problem...

In my `book` table migration, the `id` was created like this:

```php
$table->bigIncrements('id');
```

This generates a column with the MySQL data type of `bigint`.

Then, in my `book_tag` table migration, I tried to set up a foreign key relationship to the `book` table's id field like this:

```php
$table->integer('book_id')->unsigned();
$table->foreign('book_id')->references('id')->on('books');
```

And when I ran that migration it failed with the error `Cannot add foreign key constraint`.

As is explained in the video, this happened because the `book` table's `id` field was created as a `bigint` which differed from my foreign key field which was a regular `int`.

To fix, I went back and made sure all my ids were created using `bigIncrements()` and all my foreign key fields were created using `bigInteger()`.

I've also went through the notes and made sure I was consistently using the `bigint` methods.

I wanted to make this post just to echo what I went over in the video, that way if students run into the same *Cannot add foreign key constraint* error, they'll know where to look first when troubleshooting.

**Comment by susanBuck** [comment]
I was just reading through the [Laravel 5.7 -> 5.8 upgrade guide](https://laravel.com/docs/5.8/upgrade#upgrade-5.8.0), and found the section that summarizes the above point nicely:

![image](https://user-images.githubusercontent.com/237711/57151503-22a55900-6d9f-11e9-8477-74acba8accac.png)

**Comment by susanBuck** [comment]
More reading, for those who are curious about the reasoning behind the change, and just the general process of when changes like this are made in a framework that so many other applications depend on...

Here's the [pull request thread](https://github.com/laravel/framework/pull/26472), and [starting with this thread](https://github.com/laravel/framework/pull/26472#issuecomment-437693253) you can see where they start to discuss the pros/cons/reasoning of the change.

In it they reference [a situation the app Basecamp had](https://m.signalvnoise.com/update-on-basecamp-3-being-stuck-in-read-only-as-of-nov-8-922am-cst/) where their site broke when they round out of integers for an id column in a table.

Some interesting tidbits from this post:

>> At 7:21am CST, we first got alerted that we had run out of ID numbers on an important tracking table in the database. This was because the column in database was configured as an integer rather than a big integer. The integer runs out of numbers at 2147483647. The big integer can grow until 9223372036854775807.

>> At 7:29am CST, the team diagnosed the problem and started working on the fix. This meant writing what’s called a database migration where you change the column type from the regular integer to the big integer type. Changing a production database is serious business, so we had to test this fix on a staging database to make sure it was safe.

**Comment by rohanshukla9** [comment]
So how do we reference foriegn keys now?
`$table->bigIncrements('id');`
` $table->unsignedInteger('user_id')->nullable();`
`$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');`

The above code doesn't work. This is tasks table migrations
