### ISSUE TITLE
Splitting a line in PHP Storm

### ISSUE THREAD

**Issue by dianebainbridge** [susanBuck/dwa15-spring2019#55]

**Comment by dianebainbridge** [comment]
I have a long sql query that spans 2 lines in PHP Storm.  I tried to split it in 2 by using alt enter but after I did this the query did not work.
Anyone know what I might be doing wrong?

**Comment by susanBuck** [comment]
Hi Diane - Can you share the relevant code snippet?

**Comment by dianebainbridge** [comment]
Thought about that after I posted.   It's a select statement with specific columns selected and some calculated columns but I can send the exact query when I get home tonight.

**Comment by dianebainbridge** [comment]
Auth::user()->fuel_log_entries()->select(['fillup_date', 'fuel_volume', 'fuel_units','start_distance', 'end_distance', 'distance_units', \DB::raw( '(end_distance-start_distance) AS distance, CAST(((end_distance-start_distance)/fuel_volume) AS decimal(10,1)) AS fuel_consumed')])->get();

**Comment by susanBuck** [comment]
Could you update your repo with the latest code and share the URL?

That way I can clone your project and run the statement. It's a pretty complex line, so it's hard to say exactly how it can be broken up without testing to make sure it still works.

**Comment by dianebainbridge** [comment]
I did but I've having an issue with my package to export to excel right now
