### ISSUE TITLE
Windows Features under IIS use port 80

### ISSUE THREAD

**Issue by liataun** [susanBuck/dwa15-spring2019#6]
While trying to get XAMPP setup on my rather aging laptop (Windows 10 Pro 64-bit), I ran into the following issue. I am sharing what worked for me in case others have similar issues.

When starting XAMPP, Apache could not start. The standard port 80 in use mentioned in the Troubleshooting page. However, the *service using the port was the Windows NT Kernel and System process with PID 4.* This process *cannot be terminated*, so I needed to either use a different port or figure out removing port 80 from whatever was using it.

A little online searching and I was able to find a working solution. I started by uninstalling all instances of MS SQL Server based on suggestions in StackOverflow which also suggested World Wide Web Services, but didn't identify where this could be found. Removing SQL Server did not fix my issue.

Continuing down the sets of suggestions, I found this [microsoft thread](https://answers.microsoft.com/en-us/windows/forum/windows_10-start/nt-kernel-and-system-using-port-80-unable-to-stop/949669a5-8413-4b71-bcc2-65c2e2f49c44). It's a bit imperfect if you need IIS's subfeatures like World Wide Web Services, but it allow my XAMPP Apache to start. **Disable all the Windows features listed under IIS removed the port 80 listening by the PID 4 process.**

The IIS features I had running before disabling:
![windowsfeature_iis_www_on](https://user-images.githubusercontent.com/32440651/52188197-6b309300-27ff-11e9-8f9e-6a8028c04518.png)

**Comment by liataun** [comment]
Hopefully I won't find I need IIS during Spring Semester...

**Comment by susanBuck** [comment]
Great info, and good debugging procedures/documentation. Thanks for sharing, @liataun.
