### ISSUE TITLE
apache2.service restart failed

### ISSUE THREAD

**Issue by ramarolahy** [susanBuck/dwa15-spring2019#8]
I am getting the following error whenever I try to run `systemctl restart apache2.service`
```
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
```
running `systemctl status apache2.service` gives me:
 ```
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: failed (Result: exit-code) since Fri 2019-02-08 18:22:44 UTC; 21s ago
  Process: 18664 ExecStop=/usr/sbin/apachectl stop (code=exited, status=1/FAILURE)
  Process: 19562 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)
 Main PID: 17605 (code=exited, status=0/SUCCESS)
```
Running `journalctl -xe`  gives me `No journal files where found`

I had the same error this morning and I was able to locate the issue with `sudo journalctl | tail`
No success this time though.

I also tried `$ sudo service apache2 start` and `$ sudo service apache2 restart` but no success.

I am not even able to access my webpage via the DO IP/mydirectory anymore.

Any advice?

Ram

**Comment by susanBuck** [comment]
Hi Ram - Can you share the full contents of your `/etc/apache2/sites-enabled/000-default.conf` file from DigitalOcean?

**Comment by susanBuck** [comment]
Also, I searched the error message you received and found this thread: [Apache not able to restart](https://askubuntu.com/questions/629995/apache-not-able-to-restart).

Many of the answers suggest it's b/c of an error in a config file.

Try the suggestions in [this answer first](https://askubuntu.com/a/805767):

```
There is some syntax error in the file apache2.conf

In terminal type:

cd /etc/apache2

then :

apache2ctl configtest

It will show you where is the error in the apache2.conf file to correct .
```

**Comment by ramarolahy** [comment]
That fixed it thank you!
 I had a syntax error on my 000-default.conf
I added `Listen 80` at the very top earlier thinking I needed it based on the apache.org doc. I probably misread it.
