### ISSUE TITLE
DigitalOcean subdomain setup

### ISSUE THREAD

**Issue by bret-blackford** [susanBuck/dwa15-spring2019#9]

**Comment by bret-blackford** [comment]
I *think* I have followed the class instructions but having difficulty getting me domain to properly show subdomains.  I created two domains each pointing to my DigitalOcean IP of [157.230.168.85](http://157.230.168.85). Domains are:
+ www.mbret.me
+ www.bret-15dea.vip

I have added my **P1** directory and pushed everything via Git. I see the files but unable to access via web URL. 

Attached is my *000-default.conf* file.  Does order matter in this file?

.

![000-default conf](https://user-images.githubusercontent.com/11459198/52527952-5ccaf700-2c97-11e9-9e94-aa79f8dc3172.png)

**Comment by bret-blackford** [comment]
Here is how the site looks on my DreamHost account 
+ www.P1.mBret.tech

**Comment by bret-blackford** [comment]
OK. Order of entry does appear to be important with the  000-default.conf file.  I switched new entries from beginning of file to end and now I get the following link to work:
+ P1.mbret.me

but not this one:
+ P1.bret-dwa15.vip

**Comment by susanBuck** [comment]
Ah yes, time, the greater fixer of DNS issues. : ) It can be so frustrating because you just want to confirm you did things right, but the sometimes necessary wait period is out of your control.

Glad it's all sorted out now.
